name: custom-workflow
on: push
jobs: 
  job1: 
    name: ubuntu-job
    runs-on: ubuntu-latest
    steps:
    - name: print date
      run: date
  job2:
    name: windows-job
    runs-on: windows-latest
    steps:
    - name: print date
      run: date    
  job3:
    name: macos-job
    runs-on: macos-latest
    steps:
    - name: print date
      run: date    
  job4:
    name: windows-job-custom
    runs-on: windows-latest
    needs: [job1, job2, job3]
    steps:
    - name: print date
      run: date
